[general]
live_config_reload = true
import = [
 '~/.alacritty-colorscheme/themes/gruvbox_dark.toml'
]

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "None"
resize_increments = true

[font]
#normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
#normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
#normal = { family ="LigaConsolas Nerd Font", style = "Regular" }
#normal = { family = "Noto Sans Mono", style = "Medium" }
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 13
[font.offset]
x = 0
y = 0
#"LigaConsolas Nerd Font" = { liga = true, calt = true }

[env]
TERM = "xterm-256color"

[cursor]
style = { blinking = "On", shape = "beam" }

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Key1"
mods = "Control"
